Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end
  config.vm.define "dockerbuild", primary: true do |dockerbuild|
    dockerbuild.vm.hostname = "kdc.test.gokrb5"
    dockerbuild.vm.box = "centos/7"
    dockerbuild.vm.network "private_network", ip: "10.80.30.2", netmask: "255.255.0.0"
    dockerbuild.vm.provision :shell, path: "bootstrap.sh"
  end
end