Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end
  config.vm.define "vaultserver", primary: true do |vaultserver|
    vaultserver.vm.hostname = "vault.test"
    vaultserver.vm.box = "centos/7"
    vaultserver.vm.network "private_network", ip: "10.80.30.2", netmask: "255.255.0.0"
    vaultserver.vm.provision :shell, path: "bootstrap.sh"
  end
end
